// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateEmptyPipeline(arg1) {
  return window['go']['main']['App']['CreateEmptyPipeline'](arg1);
}

export function CreateNodeFromDefinition(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateNodeFromDefinition'](arg1, arg2, arg3);
}

export function GetCLIDefinitions() {
  return window['go']['main']['App']['GetCLIDefinitions']();
}

export function GetCLIDefinitionsByCategory(arg1) {
  return window['go']['main']['App']['GetCLIDefinitionsByCategory'](arg1);
}

export function GetFileListPreview(arg1, arg2) {
  return window['go']['main']['App']['GetFileListPreview'](arg1, arg2);
}

export function GetFilesFromPattern(arg1, arg2) {
  return window['go']['main']['App']['GetFilesFromPattern'](arg1, arg2);
}

export function GetStartupFilePath() {
  return window['go']['main']['App']['GetStartupFilePath']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function LoadPipeline(arg1) {
  return window['go']['main']['App']['LoadPipeline'](arg1);
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function SaveFileDialog(arg1) {
  return window['go']['main']['App']['SaveFileDialog'](arg1);
}

export function SavePipeline(arg1, arg2) {
  return window['go']['main']['App']['SavePipeline'](arg1, arg2);
}
