// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateEmptyPipeline(arg1:string):Promise<void>;

export function CreateNodeFromDefinition(arg1:string,arg2:number,arg3:number):Promise<main.CLINode>;

export function GetCLIDefinitions():Promise<Array<main.CLIDefinition>>;

export function GetCLIDefinitionsByCategory(arg1:string):Promise<Array<main.CLIDefinition>>;

export function GetEnvVariables():Promise<Record<string, string>>;

export function GetFileListPreview(arg1:string,arg2:boolean):Promise<string>;

export function GetFilesFromPattern(arg1:string,arg2:boolean):Promise<main.FileListResult>;

export function GetPathTokens():Promise<Array<main.PathToken>>;

export function GetStartupFilePath():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function LoadPipeline(arg1:string):Promise<main.Pipeline>;

export function LogFrontend(arg1:string):Promise<void>;

export function OpenFileDialog():Promise<string>;

export function RunSingleNode(arg1:main.CLINode,arg2:string):Promise<string>;

export function SaveFileDialog(arg1:string):Promise<string>;

export function SavePipeline(arg1:main.Pipeline,arg2:string):Promise<void>;
