"""
Train centroid U-Net with PyTorch Lightning.

Reads the training set produced by deep_learning_01_make_training_set.py and
trains a U-Net to predict Gaussian-blob centroid maps.

Input/output folder structure
------------------------------
<input-folder>/                             (--input-folder)
    training_set/
        input/   0.tif, 1.tif, ...          <- images
        target/  0.tif, 1.tif, ...          <- Gaussian blob maps
    model_training/                         (--output-folder, default)
        checkpoints/
            epoch001-val_loss0.0012.ckpt
            last.ckpt
        centroid_unet/                      <- TensorBoard logs

MIT License - BIPHUB, University of Oslo
"""

from __future__ import annotations

import argparse
import logging
import sys
from pathlib import Path

import torch
import pytorch_lightning as pl
from pytorch_lightning.callbacks import ModelCheckpoint, LearningRateMonitor
from pytorch_lightning.loggers import TensorBoardLogger
from torch.utils.data import DataLoader, random_split

# Import utilities from the companion file in the same directory
sys.path.insert(0, str(Path(__file__).parent))
from deep_learning_00_utils import (  # noqa: E402
    CentroidDataset,
    UNet,
    get_train_transform,
)

# Module-level logger
logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Lightning Module
# ---------------------------------------------------------------------------
class CentroidUNetModule(pl.LightningModule):
    """PyTorch Lightning wrapper for the centroid U-Net."""

    def __init__(self, lr: float = 1e-3, max_epochs: int = 200) -> None:
        super().__init__()
        self.save_hyperparameters()
        self.model = UNet(in_channels=1, out_channels=1)
        self.loss_fn = torch.nn.MSELoss()
        self.lr = lr
        self.max_epochs = max_epochs

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.model(x)

    def _shared_step(self, batch: tuple, stage: str) -> torch.Tensor:
        img, tgt = batch
        pred = self(img)
        loss = self.loss_fn(pred, tgt)
        self.log(
            f"{stage}_loss",
            loss,
            prog_bar=True,
            on_step=(stage == "train"),
            on_epoch=True,
        )
        return loss

    def training_step(self, batch: tuple, batch_idx: int) -> torch.Tensor:
        return self._shared_step(batch, "train")

    def validation_step(self, batch: tuple, batch_idx: int) -> None:
        self._shared_step(batch, "val")

    def configure_optimizers(self):
        optimizer = torch.optim.AdamW(self.parameters(), lr=self.lr)
        scheduler = torch.optim.lr_scheduler.StepLR(
            optimizer,
            step_size=max(1, self.max_epochs // 2),
            gamma=0.5,
        )
        return {"optimizer": optimizer, "lr_scheduler": scheduler}


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main() -> None:
    parser = argparse.ArgumentParser(
        description=(
            "Train a centroid U-Net on the training set generated by "
            "deep_learning_01_make_training_set.py."
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Note: --input-folder and --output-folder are used instead of the standard
--input-search-pattern convention because this script reads a fixed
folder structure (training_set/input/ and training_set/target/) rather
than a file glob, and produces a model rather than per-file outputs.

Example YAML config for run_pipeline.exe:
---
run:
- name: Train centroid U-Net (defaults)
  environment: uv@3.11:deep-learning
  commands:
  - python
  - '%REPO%/standard_code/python/deep_learning_02_train.py'
  - --input-folder: '%YAML%/deep_learning_output'

- name: Train centroid U-Net (custom hyperparameters)
  environment: uv@3.11:deep-learning
  commands:
  - python
  - '%REPO%/standard_code/python/deep_learning_02_train.py'
  - --input-folder: '%YAML%/deep_learning_output'
  - --output-folder: '%YAML%/deep_learning_output/model_training'
  - --max-epochs: 200
  - --batch-size: 16
  - --lr: 5e-4
  - --val-split: 0.15
  - --num-workers: 4

- name: Pause to inspect TensorBoard logs
  type: pause
  message: 'Run: tensorboard --logdir <output-folder>/centroid_unet'
        """,
    )

    parser.add_argument(
        "--input-folder",
        required=True,
        help=(
            "Root output folder from deep_learning_01_make_training_set.py. "
            "Must contain training_set/input/ and training_set/target/."
        ),
    )
    parser.add_argument(
        "--output-folder",
        default=None,
        help=(
            "Folder for checkpoints and TensorBoard logs. "
            "Defaults to <input-folder>/model_training/."
        ),
    )
    parser.add_argument(
        "--lr",
        type=float,
        default=1e-3,
        help="Initial learning rate for AdamW (default: 1e-3).",
    )
    parser.add_argument(
        "--batch-size",
        type=int,
        default=8,
        help="Training batch size (default: 8).",
    )
    parser.add_argument(
        "--max-epochs",
        type=int,
        default=100,
        help="Maximum training epochs (default: 100).",
    )
    parser.add_argument(
        "--val-split",
        type=float,
        default=0.15,
        help="Fraction of data used for validation (default: 0.15).",
    )
    parser.add_argument(
        "--num-workers",
        type=int,
        default=4,
        help="DataLoader worker processes (default: 4).",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=42,
        help="Random seed for reproducibility (default: 42).",
    )
    parser.add_argument(
        "--log-level",
        type=str,
        default="INFO",
        choices=["DEBUG", "INFO", "WARNING", "ERROR"],
        help="Logging level (default: INFO).",
    )

    args = parser.parse_args()

    logging.basicConfig(
        level=getattr(logging, args.log_level),
        format="%(asctime)s - %(levelname)s - %(message)s",
    )

    # ------------------------------------------------------------------ #
    # Resolve paths                                                        #
    # ------------------------------------------------------------------ #
    input_folder = Path(args.input_folder).resolve()
    train_input_dir = input_folder / "training_set" / "input"
    train_target_dir = input_folder / "training_set" / "target"

    if not train_input_dir.is_dir():
        raise SystemExit(
            f"Expected training input folder not found: {train_input_dir}\n"
            "Run deep_learning_01_make_training_set.py first."
        )
    if not train_target_dir.is_dir():
        raise SystemExit(
            f"Expected training target folder not found: {train_target_dir}\n"
            "Run deep_learning_01_make_training_set.py first."
        )

    output_folder = (
        Path(args.output_folder).resolve()
        if args.output_folder is not None
        else input_folder / "model_training"
    )
    output_folder.mkdir(parents=True, exist_ok=True)

    logger.info("Input folder       : %s", input_folder)
    logger.info("Training input dir : %s", train_input_dir)
    logger.info("Training target dir: %s", train_target_dir)
    logger.info("Output folder      : %s", output_folder)

    # ------------------------------------------------------------------ #
    # Seed everything                                                      #
    # ------------------------------------------------------------------ #
    pl.seed_everything(args.seed, workers=True)

    # ------------------------------------------------------------------ #
    # Datasets & data loaders                                              #
    # ------------------------------------------------------------------ #
    full_ds = CentroidDataset(train_input_dir, train_target_dir, transform=None)
    n_total = len(full_ds)
    if n_total == 0:
        raise SystemExit(f"No images found in {train_input_dir}")

    n_val = max(1, int(n_total * args.val_split))
    n_train = n_total - n_val
    logger.info("Dataset: %d total, %d train, %d val", n_total, n_train, n_val)

    train_ds, val_ds = random_split(
        full_ds,
        [n_train, n_val],
        generator=torch.Generator().manual_seed(args.seed),
    )

    # Apply augmentation to training subset only
    train_ds.dataset = CentroidDataset(
        train_input_dir,
        train_target_dir,
        transform=get_train_transform(),
    )

    train_loader = DataLoader(
        train_ds,
        batch_size=args.batch_size,
        shuffle=True,
        num_workers=args.num_workers,
        pin_memory=True,
        persistent_workers=args.num_workers > 0,
    )
    val_loader = DataLoader(
        val_ds,
        batch_size=args.batch_size,
        shuffle=False,
        num_workers=args.num_workers,
        pin_memory=True,
        persistent_workers=args.num_workers > 0,
    )

    # ------------------------------------------------------------------ #
    # Model                                                                #
    # ------------------------------------------------------------------ #
    model = CentroidUNetModule(lr=args.lr, max_epochs=args.max_epochs)

    # ------------------------------------------------------------------ #
    # Callbacks & logger                                                   #
    # ------------------------------------------------------------------ #
    tb_logger = TensorBoardLogger(
        save_dir=str(output_folder),
        name="centroid_unet",
    )

    checkpoint_cb = ModelCheckpoint(
        dirpath=str(output_folder / "checkpoints"),
        filename="epoch{epoch:03d}-val_loss{val_loss:.4f}",
        monitor="val_loss",
        mode="min",
        save_top_k=3,
        save_last=True,
        auto_insert_metric_name=False,
    )

    lr_monitor = LearningRateMonitor(logging_interval="epoch")

    # ------------------------------------------------------------------ #
    # Trainer                                                              #
    # ------------------------------------------------------------------ #
    trainer = pl.Trainer(
        max_epochs=args.max_epochs,
        accelerator="auto",
        devices=1,
        logger=tb_logger,
        callbacks=[checkpoint_cb, lr_monitor],
        log_every_n_steps=1,
        deterministic=True,
    )

    tb_log_dir = output_folder / "centroid_unet"
    logger.info("")
    logger.info("=" * 60)
    logger.info("TensorBoard: open a separate terminal and run:")
    logger.info("  tensorboard --logdir \"%s\"", tb_log_dir)
    logger.info("Then open: http://localhost:6006")
    logger.info("=" * 60)
    logger.info("")

    trainer.fit(model, train_dataloaders=train_loader, val_dataloaders=val_loader)

    logger.info("Best checkpoint : %s", checkpoint_cb.best_model_path)
    logger.info("TensorBoard logs: %s", tb_log_dir)
    logger.info("  -> tensorboard --logdir \"%s\"", tb_log_dir)


if __name__ == "__main__":
    main()
