"""
Generate NIS-Elements macro to reassemble split TIFF files into ND2 format.
Reads metadata YAML to determine dimensions and creates appropriate ND_Convert calls.

MIT License - BIPHUB, University of Oslo
"""

import os
import argparse
import logging
from pathlib import Path
from typing import Optional
import yaml

# Module-level logger
logger = logging.getLogger(__name__)


def generate_macro(
    split_folder: str,
    output_nd2: str,
    metadata_yaml: Optional[str] = None
) -> str:
    """
    Generate NIS-Elements macro to reassemble split TIFF files.
    
    Args:
        split_folder: Path to folder containing split TIFF files
        output_nd2: Path where ND2 file should be saved
        metadata_yaml: Path to metadata YAML file (if not provided, looks for _metadata.yaml)
    
    Returns:
        Path to generated macro file
    """
    # Find metadata file if not provided
    if metadata_yaml is None:
        # Look for _metadata.yaml in parent folder
        parent = os.path.dirname(split_folder)
        basename = os.path.basename(split_folder)
        metadata_yaml = os.path.join(parent, basename + "_metadata.yaml")
    
    if not os.path.exists(metadata_yaml):
        raise FileNotFoundError(f"Metadata file not found: {metadata_yaml}")
    
    logger.info(f"Reading metadata from: {metadata_yaml}")
    
    # Load metadata
    with open(metadata_yaml, 'r', encoding='utf-8') as f:
        metadata = yaml.safe_load(f)
    
    # Extract dimensions from metadata
    # Try different metadata structures
    T, C, Z = 1, 1, 1
    time_interval_us = 1000000  # Default 1 second
    z_step_um = 1.0  # Default 1 micron
    channel_names = []
    
    # Try to find dimensions in metadata
    if 'Shape' in metadata:
        shape = metadata['Shape']
        T = shape.get('T', 1)
        C = shape.get('C', 1)
        Z = shape.get('Z', 1)
    elif 'Dimensions' in metadata:
        dims = metadata['Dimensions']
        T = dims.get('T', 1)
        C = dims.get('C', 1)
        Z = dims.get('Z', 1)
    
    # Try to find time interval
    if 'PhysicalSizeT' in metadata:
        # Time in seconds, convert to microseconds
        time_interval_us = int(metadata['PhysicalSizeT'] * 1_000_000)
    elif 'Time' in metadata:
        if isinstance(metadata['Time'], dict) and 'Interval' in metadata['Time']:
            time_interval_us = int(metadata['Time']['Interval'] * 1_000_000)
    
    # Try to find Z step
    if 'PhysicalSizeZ' in metadata:
        z_step_um = metadata['PhysicalSizeZ']
    elif 'Z' in metadata:
        if isinstance(metadata['Z'], dict) and 'Step' in metadata['Z']:
            z_step_um = metadata['Z']['Step']
    
    # Try to find channel names
    if 'Channels' in metadata:
        if isinstance(metadata['Channels'], list):
            channel_names = metadata['Channels']
        elif isinstance(metadata['Channels'], dict):
            channel_names = list(metadata['Channels'].values())
    
    # Ensure we have enough channel names
    if len(channel_names) < C:
        for i in range(len(channel_names), C):
            channel_names.append(f"Channel_{i}")
    
    logger.info(f"Dimensions: T={T}, C={C}, Z={Z}")
    logger.info(f"Time interval: {time_interval_us} µs ({time_interval_us/1_000_000:.3f} s)")
    logger.info(f"Z step: {z_step_um} µm")
    logger.info(f"Channels: {channel_names[:C]}")
    
    # Find first TIFF file
    first_file = os.path.join(split_folder, "T0000_C0000_Z0000_S0000.tif")
    if not os.path.exists(first_file):
        raise FileNotFoundError(f"First TIFF file not found: {first_file}")
    
    # Normalize paths for NIS-Elements (backslashes)
    first_file_nis = first_file.replace('/', '\\')
    output_nd2_nis = output_nd2.replace('/', '\\')
    
    # Generate macro content
    macro_lines = [
        "// Auto-generated macro to reassemble split TIFF files into ND2",
        "// Generated by generate_nis_reassembly_macro.py",
        "",
        "int64 iHandle;",
        "double *pXYCoords;",
        "",
        f'iHandle = ND_ConvertInit("{first_file_nis}", 0, {C}, 3, 1);',
        ""
    ]
    
    # Add time loop if T > 1
    if T > 1:
        macro_lines.append(f"ND_ConvertSetTimeLoop(iHandle, {T}, {time_interval_us});")
    
    # Add Z stack loop if Z > 1
    if Z > 1:
        macro_lines.append(f"ND_ConvertSetZStackLoop(iHandle, {Z}, {z_step_um:.6f});")
    
    # Add XY loop (single position for now)
    macro_lines.extend([
        "",
        "pXYCoords = ND_ConvertAllocXYCoors(2);",
        "pXYCoords[0] = 0;",
        "pXYCoords[1] = 0;",
        "ND_ConvertSetXYLoop(iHandle, 1, 0, pXYCoords);",
        ""
    ])
    
    # Add wavelengths (channels)
    for i in range(C):
        channel_name = channel_names[i] if i < len(channel_names) else f"Channel_{i}"
        # Use white color (16777215) for all channels
        macro_lines.append(f'ND_ConvertAddWaveLength(iHandle, 16777215, "{channel_name}", "");')
    
    # Finish conversion and open
    macro_lines.extend([
        "",
        f'ND_ConvertFinish(iHandle, "{output_nd2_nis}");',
        f'OpenDocument("{output_nd2_nis}", 0);',
        ""
    ])
    
    # Write macro file
    macro_path = os.path.join(split_folder, "reassemble_to_nd2.mac")
    with open(macro_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(macro_lines))
    
    logger.info(f"Generated macro: {macro_path}")
    
    return macro_path


def main() -> None:
    """Main CLI entry point."""
    parser = argparse.ArgumentParser(
        description="Generate NIS-Elements macro to reassemble split TIFF files.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Generate macro for a split folder
  python generate_nis_reassembly_macro.py --split-folder "data/image_folder" --output-nd2 "data/image.nd2"
  
  # Specify custom metadata file
  python generate_nis_reassembly_macro.py --split-folder "data/image_folder" --output-nd2 "data/image.nd2" --metadata "data/custom_metadata.yaml"
        """
    )
    
    parser.add_argument(
        "--split-folder",
        type=str,
        required=True,
        help="Path to folder containing split TIFF files"
    )
    
    parser.add_argument(
        "--output-nd2",
        type=str,
        required=True,
        help="Path where ND2 file should be saved"
    )
    
    parser.add_argument(
        "--metadata",
        type=str,
        default=None,
        help="Path to metadata YAML file (default: auto-detect)"
    )
    
    args = parser.parse_args()
    
    # Setup logging
    logging.basicConfig(
        level=logging.INFO,
        format='%(asctime)s | %(levelname)s | %(message)s',
        datefmt='%Y-%m-%d %H:%M:%S'
    )
    
    # Generate macro
    try:
        macro_path = generate_macro(
            split_folder=args.split_folder,
            output_nd2=args.output_nd2,
            metadata_yaml=args.metadata
        )
        print(f"Success! Macro generated at: {macro_path}")
        print(f"Run this macro in NIS-Elements to create: {args.output_nd2}")
    except Exception as e:
        logger.error(f"Failed to generate macro: {e}")
        raise


if __name__ == "__main__":
    main()
